name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Build JARs for each module
    - name: Build Auth Service
      run: mvn clean package -pl backend/service-auth

    - name: Build Post Service
      run: mvn clean package -pl backend/service-post

    - name: Build Message Service
      run: mvn clean package -pl backend/service-message
    
    - name: Build Profile Service
      run: mvn clean package -pl backend/service-profile
    
    - name: Build API Gateway
      run: mvn clean package -pl backend/apigateway
    
    - name: Build Euruka Server
      run: mvn clean package -pl backend/eurukaserver

    # Login to ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    # Build & Push Docker Images
    - name: Build and Push Auth Service
      run: |
        docker build -t auth-service:latest ./backend/service-auth
        docker tag auth-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

    - name: Build and Push Post Service
      run: |
        docker build -t post-service:latest ./backend/service-post
        docker tag post-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/post-service:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/post-service:latest

    - name: Build and Push Message Service
      run: |
        docker build -t message-service:latest ./backend/service-message
        docker tag message-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/message-service:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/message-service:latest
    
    - name: Build and Push Profile Service
      run: |
        docker build -t profile-service:latest ./backend/service-profile
            docker tag profile-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/profile-service:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/profile-service:latest
    
    - name: Build and Push API Gateway
      run: |
        docker build -t api-gateway:latest ./backend/apigateway
        docker tag api-gateway:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/api-gateway:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/api-gateway:latest
    
    - name: Build and Push Euruka Server
      run: |
        docker build -t euruka-server:latest ./backend/eurukaserver
        docker tag euruka-server:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/euruka-server:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/euruka-server:latest
    
